name: Send File Content on Push

on:
  push:
    branches:
      - main  # Change this to your desired branch

jobs:
  send_file_content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Send Modified File Content
        env:
          WEBHOOK_URL: http://3.110.87.221/scan  # Replace with your actual webhook URL
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}  # Store your secret in GitHub Secrets
        run: |
          for file in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }}); do
            content=$(cat "$file")
            payload="{\"file_path\": \"$file\", \"file_content\": \"$content\"}"
            signature=$(echo -n "$payload" | openssl dgst -sha256 -hmac "$WEBHOOK_SECRET" | cut -d ' ' -f2)
            curl -X POST $WEBHOOK_URL \
              -H "Content-Type: application/json" \
              -H "X-Hub-Signature-256: sha256=$signature" \
              -d "$payload"
          done
