
name: Scan on Commit

on:
  push:
    branches:
      - main  # Or whichever branch you want to monitor
    paths:
      - e-commerce.py  # This will trigger only if e-commerce.py is changed

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Scan Script with curl
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
        run: |
          curl -X POST https://scanner-saom.onrender.com/scan \
          -H "Content-Type: application/json" \
          -d '{
            "file_path": "e-commerce.py",
            "db_host": "'"${{ secrets.DB_HOST }}"'",
            "db_user": "'"${{ secrets.DB_USER }}"'",
            "db_password": "'"${{ secrets.DB_PASSWORD }}"'",
            "db_name": "'"${{ secrets.DB_NAME }}"'",
            "db_port": "'"${{ secrets.DB_PORT }}"'"
          }'
